kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Chart.Name}}-role-binding
subjects:
  - kind: ServiceAccount
    name: {{ .Chart.Name}}
roleRef:
  kind: ClusterRole
  name: {{ .Chart.Name}}