apiVersion: v1
data:
  # Configuration is in Json format. No matter what configure change you make,
  # please keep the Json blob valid.
  cwagentconfig.json: |
    {
      "agent": {
        "region": {{ .Values.cluster.region }}
      },
      "logs": {
        "metrics_collected": {
          "kubernetes": {
            "cluster_name": {{ .Values.cluster.name }},
            "metrics_collection_interval": 60
          }
        },
        "force_flush_interval": 5
      }
    }
kind: ConfigMap
metadata:
  name: cwagentconfig